name: Deploy Backend .NET

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 📦 Checkout do código
      - name: Checkout
        uses: actions/checkout@v4

      # 🔐 Login no Docker Hub
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # 🐳 Build da imagem
      - name: Build image
        run: docker build -t mantecsystems/mantec2-back:latest .

      # 📤 Push da imagem
      - name: Push image
        run: docker push mantecsystems/mantec2-back:latest

      # 🚀 Deploy via Stack no Swarm
      - name: Deploy no servidor via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Forçar o download da imagem mais recente no servidor
            docker pull mantecsystems/mantec2-back:latest
            
            # 2. Entrar na pasta onde estão os seus arquivos .yml
            cd ~/stacks/05-apps
            
            # 3. Atualizar a stack 'm2' usando o arquivo mantec2.yml
            # O Swarm detectará a mudança na imagem e fará o Rolling Update automaticamente.
            docker stack deploy -c mantec2.yml m2
