name: Deploy Backend .NET

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Definir versão
        run: |
          echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build \
            -t mantecsystems/mantec2-back:latest \
            -t mantecsystems/mantec2-back:${IMAGE_TAG} \
            .

      - name: Push image
        run: |
          docker push mantecsystems/mantec2-back:latest
          docker push mantecsystems/mantec2-back:${IMAGE_TAG}

      - name: Atualizar stack
        run: |
          docker pull mantecsystems/mantec2-back:latest

          docker stack deploy \
            -c /home/lemuel/stacks/05-apps/mantec2.yml \
            mantec2

      - name: Verificar deploy
        run: |
          docker stack services mantec2